apiVersion: core.choreo.dev/v1alpha1
kind: ComponentConfig
metadata:
  name: user
  projectName: pet-store
  annotations:
    componentType: service
spec:
  inbound:
  - name: user
    port: 9092
    type: REST
    visibility: Project
    context: /
  outbound:
    serviceReferences:
    - name: user-db
      dependentConfig: config-1
      connectionType: datastore
