apiVersion: core.choreo.dev/v1alpha1
kind: ComponentConfig
metadata:
  name: order
  projectName: pet-store
  annotations:
    componentType: service
spec:
  inbound:
  - name: order
    port: 9091
    type: REST
    visibility: Public
    context: /
  outbound:
    serviceReferences:
    - name: choreo:///madusha/lpar/btpmlu/40c92b81-2ddd-4933-9422-a920b7e27736/v1.0/inventory/public
      dependentConfig: config-1
      connectionType: service
    - name: choreo:///madusha/lpar/cnukze/40c92b81-2ddd-4933-9422-a920b7e27736/v1.0/user/project
      dependentConfig: config-1
      connectionType: service
    - name: choreo:///madusha/lpar/vtfqif/40c92b81-2ddd-4933-9422-a920b7e27736/v1.0/notification/project
      dependentConfig: config-1
      connectionType: service
    - name: choreo:///kanushka/lpar/cnukze/40c92b81-2ddd-4933-9422-a920b7e27736/v1.0/sales
      dependentConfig: config-1
      connectionType: service
