apiVersion: core.choreo.dev/v1alpha1
kind: ComponentConfig
metadata:
  name: review
  projectName: pet-store
  annotations:
    componentType: service
spec:
  inbound:
  - name: review
    port: 9099
    type: REST
    visibility: Public
    context: /
  outbound:
    serviceReferences:
    - name: choreo://pet-store/checkout/v1.0/checkout/public
      dependentConfig: config-1
      connectionType: service
